name: phone_number_example
description: Demonstrates how to use the phone_number plugin.
publish_to: 'none'
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  e2e: ^0.4.0
  flutter_driver:
    sdk: flutter
  
  phone_number:
    path: ../

flutter:
  uses-material-design: true
